#define MOTOR_STEPS_PER_REV 200
#define PRES_MICRO_STEP 1
#define PRES_TOOTH_PITCH 2
#define PRES_PULLEY_TEETH 20
#define PRES_DIRECTION 1

#define PRES_SIGNAL_STEPS_PER_REV  MOTOR_STEPS_PER_REV*PRES_MICRO_STEP
#define PRES_MM_PER_REV PRES_TOOTH_PITCH*PRES_PULLEY_TEETH
#define PRES_SIGNAL_STEPS_PER_MM PRES_SIGNAL_STEPS_PER_REV/PRES_MM_PER_REV

#define REV_GEAR_RATIO 1
#define REV_SIGNAL_STEPS_PER_REV  MOTOR_STEPS_PER_REV*PRES_MICRO_STEP*REV_GEAR_RATIO
#define REV_SIGNAL_STEPS_PER_RAD REV_SIGNAL_STEPS_PER_REV/360
#define REV_DIRECTION 1



#define FORWARD 1
#define REVERSE 0

#define REVOLUTE_PIN_DIR    5
#define REVOLUTE_PIN_STEP   2

#define PERSIMITIC_PIN_DIR    6
#define PERSIMITIC_PIN_STEP   3

#define COMPLETE_REVOLUTION   200


